os: osx

cache:
  ccache: true
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.pyenv
    - $HOME/Library/Caches/pip
    - /usr/local/Cellar
    - /usr/local/Caskroom
    - /usr/local/opt

env:
  - TRAVIS=1

branches:
  only:
    - osx

before_cache:
  - brew cleanup

before_install:
  - test -x /usr/local/bin/ansible || brew install ansible
  - test -x /usr/local/bin/ccache || brew install ccache

install:
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"

script:
  - git clone https://github.com/benmezger/dotfiles.git ~/dotfiles
  - (cd ~/dotfiles; git checkout osx)
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook -i inventory osx.yml
