env:
  - TRAVIS=1

install:
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"

matrix:
  include:
    - os: osx
      env:
        - CACHE_NAME=osx
      before_install:
        - brew upgrade python
        - test -x /usr/local/bin/ansible || brew install ansible
        - test -x /usr/local/bin/ccache || brew install ccache
      script:
        - ansible-galaxy install -r requirements.yml
        - ansible-playbook -i inventory osx.yml
      before_cache:
        - brew cleanup
      cache:
        ccache: true
        pip: true
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/.pyenv
          - $HOME/Library/Caches/pip
          - /usr/local/Cellar
          - /usr/local/Caskroom
          - /usr/local/opt
    - os: linux
      env:
        - CACHE_NAME=linux
      cache:
        bundler: true
        directories:
          - $HOME/docker
      language: minimal
      addons:
        apt:
          packages:
            - docker-ce
      before_cache:
        - >
          mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
          | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
      before_install:
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
      script:
        - docker-compose up --exit-code-from dotfiles
