---
- hosts: localhost
  roles:
    - role: archlinux
    - role: common
    - role: linux
    - role: kewlfft.aur
    - role: markosamuli.pyenv
      vars:
        - pyenv_python3_version: "3.7.3"
        - pyenv_python_versions:
            - "{{ pyenv_python3_version }}"
        - pyenv_global: "{{ pyenv_python3_version }} system"
        - pyenv_virtualenvwrapper: true
        - pyenv_detect_existing_install: true
        - pyenv_init_shell: false
        - pyenv_install_from_package_manager: false
