---
- name: Create aur user
  become: true
  user:
    name: aur_builder
    group: wheel

- name: Add aur user to sudoers
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"

- name: Install Trizen
  become_user: aur_builder
  aur:
    name:
      - trizen
    use: makepkg
    state: present

- import_tasks: pacman.yml
