---
- name: Install Pacman packages
  become: true
  command: pacman -S {{ item }} --noconfirm
  with_items:
    - python2
    - python2-pip
    - vim
    - fasd
    - ack
    - gnupg2
    - tmux
    - tor
    - valgrind
    - zsh
    - xorg-xset
    - xorg-xrdb
    - dunst
    - pcsclite
    - feh
    - pcsc-tools
    - scrot
    - xautolock
    - wget
    - rofi
    - openssh
    - lxappearance
    - ccid
    - imagemagick
    - cmake
    - libu2f-host
    - linux-zen
    - linux-zen-headers
    - linux-headers
    - neovim
    - gnome-keyring
    - acpi
    - gdb
    - unrar
    - zathura-pdf-mupdf
    - redshift
    - networkmanager
    - network-manager-applet
    - networkmanager-openvpn
    - noto-fonts-emoji
    - ttf-symbola
    - ttf-font-awesome
    - the_silver_searcher
    - vagrant
    - docker
    - htop
    - urxvt-perls
    - rxvt-unicode
    - xf86-input-evdev
    - xf86-input-mouse
    - xf86-input-keyboard
    - xf86-video-intel
    - slim
    - qt5-base
    - fish
    - base-devel
    - openssl
    - zlib
    - xz

- name: Install AUR packages
  become: yes
  become_user: aur_builder
  aur:
    use: pacaur
    name:
      - xss-lock
      - spotify
      - numix-icon-theme-git
      - gitter
      - dropbox
      - git-crypt
      - otf-inconsolata-dz
      - pairing_tool
      - emacs27-git
