---
- name: Sync Pacman
  become: true
  pacman:
    update_cache: yes

- name: Install Pacman packages
  become: true
  shell:
    pacman -S $(< {{ playbook_dir }}/roles/archlinux/tasks/pkgs.pacman) \
    --noconfirm --needed

- name: Install AUR packages
  become_user: aur_builder
  aur:
    state: present
    use: trizen
    name:
      - ttf-symbola
      - gtk-theme-arc-gruvbox-git
