---
- name: Sync Pacman
  become: true
  pacman:
    update_cache: yes

- name: Enable pacman.conf options
  become: true
  shell:
    sed -i '/Color$/s/^#//g' /etc/pacman.conf
    sed -i '/TotalDownload$/s/^#//g' /etc/pacman.conf
    sed -i '/CheckSpace$/s/^#//g' /etc/pacman.conf
    sed -i '/VerbosePkgLists$/s/^#//g' /etc/pacman.conf

- name: Install Pacman packages
  become: true
  shell:
    pacman -S $(< {{ playbook_dir }}/roles/archlinux/tasks/pkgs.pacman) \
    --noconfirm --needed
