---

- stat:
    path: "~/.pyenv/bin"
  register: pyenv_installed

- name: Install Pyenv
  shell: curl https://pyenv.run | bash
  when: pyenv_installed.stat.exists == False
  args:
    warn: no

- name: Install Python using pyenv
  command: "~/.pyenv/bin/pyenv install 3.7.3"

- name: Set global Python version
  command: "~/.pyenv/bin/pyenv global 3.7.3"
