---
- name: Tap fonts
  poll: 0
  async: 45
  register: tapfonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Tap Emacs 28
  poll: 0
  async: 45
  register: tapemacs
  homebrew_tap:
    name: d12frosted/emacs-plus
    state: present

- name: Install Emacs 28
  homebrew:
    install_options: with-jansson
    state: latest
    name:
      - emacs-plus@28

- name: Install Homebrew packages
  poll: 0
  async: 45
  register: brewpkgs
  homebrew:
    state: latest
    upgrade_all: yes
    name:
      - vim
      - fasd
      - ack
      - gnupg2
      - tmux
      - tor
      - reattach-to-user-namespace
      - pinentry-mac
      - git
      - the_silver_searcher
      - diff-so-fancy
      - cmake
      - mas
      - fish
      - xz
      - readline
      - pyenv
      - go
      - cquery
      - clang-format
      - unrar
      - automake
      - cmake
      - coreutils
      - git-chglog
      - neovim
      - fzf
      - wakatime-cli
      - ripgrep
      - antibody
      - exa
      - pandoc
      - hugo
      - pre-commit

- name: Install apps using Homebrew Cask
  poll: 0
  async: 45
  become: true
  register: brewcasks
  homebrew_cask:
    name: "{{ item }}"
    state: present
    upgrade_all: yes
  with_items:
    - firefox
    - transmission
    - alacritty
    - vlc
    - skype
    - spotify
    - docker
    - 1password
    - hopper-disassembler
    - java
    - ckb-next
    - insomnia
    - stremio
    - maccy
    - syncthing
    - postgres

- name: Install fonts using Homebrew Cask
  poll: 0
  async: 45
  when: tapfonts is succeeded
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - font-inconsolata-dz
    - Hack

- name: Cleanup Homebrew packages
  poll: 0
  async: 45
  when: (brewpkgs is succeeded) and (brewcasks is succeeded)
  command: brew cleanup -s
