---
- name: Tap fonts
  poll: 0
  async: 45
  register: tapfonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install Homebrew packages
  poll: 0
  async: 45
  register: brewpkgs
  homebrew:
    state: latest
    upgrade_all: yes
    name:
      - vim
      - fasd
      - ack
      - gnupg2
      - tmux
      - tor
      - reattach-to-user-namespace
      - stow
      - pinentry-mac
      - git
      - the_silver_searcher
      - diff-so-fancy
      - cmake
      - mas
      - fish
      - xz
      - readline
      - pyenv
      - go
      - cquery
      - clang-format
      - unrar
      - automake
      - cmake
      - coreutils
      - git-chglog
      - neovim

- name: Install apps using Homebrew Cask
  poll: 0
  async: 45
  become: true
  register: brewcasks
  homebrew_cask:
    name: "{{ item }}"
    state: present
    upgrade_all: yes
  with_items:
    - brave-browser
    - transmission
    - alacritty
    - vlc
    - skype
    - spotify
    - docker
    - 1password
    - hopper-disassembler
    - java
    - ckb-next
    - insomnia
    - stremio
    - maccy
    - syncthing

- name: Install fonts using Homebrew Cask
  poll: 0
  async: 45
  when: tapfonts is succeeded
  homebrew_cask:
    name: font-inconsolata-dz
    state: present

- name: Cleanup Homebrew packages
  poll: 0
  async: 45
  when: (brewpkgs is succeeded) and (brewcasks is succeeded)
  command: brew cleanup -s
