---
- import_tasks: brew.yml
# - import_tasks: "{{ playbook_dir }}/roles/common/tasks/python.yml"
- import_tasks: mas.yml
  when: lookup('env', 'TRAVIS') == '0'

- name: Restore files using GNU Stow
  command: stow {{ item }}
  poll: 0
  async: 45
  args:
    chdir: ~/dotfiles
  with_items:
    - bin
    - git
    - gnupg
    - ipython
    - misc
    - tmux
    - vim
    - zsh
    - fish
    - emacs

- name: Ensure vim directories exist
  poll: 0
  async: 45
  file:
    path: ~/.vim/autoload
    state: directory

- name: Install Vim-Plug
  poll: 0
  async: 45
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Copy Tmux launchd daemon
  poll: 0
  async: 45
  become: true
  command: cp {{ playbook_dir }}/roles/osx/tasks/confs/com.tmux.plist /Library/LaunchDaemons/

- name: Make launchd start tmux on boot
  poll: 0
  async: 45
  become: true
  command: launchctl load -w /Library/LaunchDaemons/com.tmux.plist
