[greenclip]
history_file = "~/.cache/greenclip.history"
max_history_length = 15000
max_selection_size_bytes = 0
trim_space_from_selection = true
use_primary_selection_as_input = false
blacklisted_applications = [bitwarden-cli, bw]
enable_image_support = true
