name: dotfiles
on: push

jobs:
  archlinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull docker image
        run: docker-compose pull

      - name: Run installer on Archlinux
        run: docker-compose up --build --exit-code-from dotfiles
  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Cache homebrew packages
        uses: actions/cache@v2
        env:
          cache-name: cache-installed-packages
        with:
          path: |
            $HOME/Library/Caches/Homebrew
            $HOME/.pyenv
            $HOME/Library/Caches/pip
            /usr/local/Caskroom
            /usr/local
            $HOME/Applications
            /Applications
          key: homebrew-${{ runner.os }}
          restore-keys: |
            homebrew-${{ runner.os }}
      - name: Install Ansible
        run: brew install ansible
      - name: Install Ansible galaxies
        run: ansible-galaxy install -r requirements.yml
      - name: Run Ansible
        run: ansible-playbook -i inventory osx.yml
